[app]
log_level = "debug" # `debug` for verbose logs. `info` otherwise.
env = "dev" # dev|prod.
dry_run = true # set to true if you don't want the DNS records to be actually created.
sync_interval = "10s" # Interval at which the records are synced from Nomad to DNS providers.

[dns]
provider = "route53"
domain_filters = ["test.internal"]

[provider.route53]
region = "ap-south-1"
max_retries = 5
