[app]
log_level = "debug" # `debug` for verbose logs. `info` otherwise.
env = "dev" # dev|prod.
dry_run = true # set to true if you don't want the DNS records to be actually created.
update_interval = "10s" # Interval at which the records are synced from Nomad to DNS providers.
prune_interval = "1h" # Interval at which any extra records that exist in DNS providers but doesn't exist in Nomad cluster are cleaned up. It maybe an expensive operation with some DNS providers like AWS R53 to do this so keep a higher interval (preferably in order of a few minutes)

[dns]
provider = "route53"
domain_filters = ["test.internal"]
created_by_key = "nomad-external-dns" # This key is used to identify the records created by this tool. Records without this key will be ignored.

[provider.route53]
region = "ap-south-1"
max_retries = 5
